# Generated by Django 4.1.4 on 2022-12-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='Activity_log',
            field=models.CharField(choices=[('Not Active', 'Not Active'), ('Active', 'Active')], default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=False, max_length=6),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Outcome',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
    ]
