# Generated by Django 4.1.4 on 2022-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0003_alter_testmodel_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=6),
        ),
    ]
