# Generated by Django 4.1.4 on 2022-12-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0004_alter_testmodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='Activity_log',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='Outcome',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='Weight',
        ),
    ]
