# Generated by Django 4.1.4 on 2022-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0005_remove_testmodel_activity_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='Height',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='Weight',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
