# Generated by Django 4.1.4 on 2022-12-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0007_testmodel_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='Gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
