# Generated by Django 4.1.4 on 2022-12-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0008_testmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='Activity',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
